INSERT INTO GAUser
	VALUES(001,'USER1@ETSU.EDU', 'TEST1', 'REVIEWER', 'ACTIVE')
;
INSERT INTO GAUser
	VALUES(002,'USER2@ETSU.EDU', 'TEST2', 'GRADCOORD', 'ACTIVE')
;


INSERT INTO Student
	VALUES('E5555555','JACOB','MIDDLE','HOYOS',2,'JH@ETSU.EDU')
;
INSERT INTO Student
	VALUES('E5555556','MARY','MIDDLE','SNODDY',2,'MS@ETSU.EDU')
;

INSERT INTO Application
	VALUES(000001, '1/1/2019', 'E5555555',1,1)
;
INSERT INTO Application
	VALUES(000002, '1/1/2019', 'E5555556',2,2)
;

INSERT INTO Concentration
	VALUES(1, 'Information Technology')
;
INSERT INTO Concentration
	VALUES(2, 'Information Systems')
;

INSERT INTO Job
	VALUES(001, 'Teaching Assistant', 5.00, 'Bennett', 101, 'A')
;
INSERT INTO Job
	VALUES(002, 'Grader',4.00, 'Bennett', 102, 'B')
;


/*
NOTES FOR DEMO SPRINT 2:

	- DEMO INCLUDES LOG IN, SUTDENT/ APPLICATION SEARCH
	
	- 2 USER TYPES REVIEWER AND GRAD COORDINATOR, AT THIS TIME VIEW IS SAME
		- GRAD COORDINATOR WILL HAVE MORE MANAGMENT OPTIONS
	
	- THERE IS A LINK TO CREATE A NEW APPLICATION, IS NOT ACTIVE AT THIS TIME, WILL BE ON NEXT SPRINT
	
	- A LINK FROM THE SEARCH RESULTS WILL TAKE THE USER TO THE FULL APPLICATION, WILL BE ON NEXT SPRINT

	- 
	
*/